import mongoose from "mongoose";

const transactionSchema = new mongoose.Schema({
    fromAccount: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "accountModel",
        required: [true, "Transaction must be associated with a from account"],
        index: true
    },

    toAccount: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "accountModel",
        required: [true, "Transaction must be associated with a to account"],
        index: true
    },
    status: {
        type: String,
        enum: {
            values: ["PENDING", "COMPLETE", "FAILED", "REVERSED"],
            message: "Status can either be PENDING,COMPLETE,FAILED or REVERSED"
        },
        default: "PENDING"
    },

    amount: {
        type: Number,
        required: [true, "Amount is required for creating a transaction"],
        min: [0, "Transaction amount cannot be negative"]
    },

    category: {
        type: String,
        eum: ["TRANSFER", "FOOD", "SHOPPING", "UTILITIES", "ENTERTAINMENT", "OTHER"],
        default: "TRANSFER"
    },

    idempotencyKey://Always generated by a client
    {
        type: String,
        required: [true, "Idempotency key is required for a transaction"],
        index: true,
        unique: true
    }

}, { timestamps: true })

const transactionModel = mongoose.model("transactionModel", transactionSchema);

export { transactionModel }